name: CI - Terraform on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    # test
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.9.8

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Login to Azure using Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Initialize Terraform
        run: |
          cd terraform/vm  
          terraform init

      - name: "Terraform Validate"
        run: terraform validate
        working-directory: terraform/vm  

      - name: Plan Terraform
        run: |
          cd terraform/vm  
          echo "Planning Terraform..."
          terraform plan \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"  
            -var="subscription_id=${{ secrets.AZURE_CREDENTIALS.subscription_id }}"

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform/vm  
          echo "Applying Terraform..."
          terraform apply -auto-approve \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
            -var="subscription_id=${{ secrets.AZURE_CREDENTIALS.subscription_id }}"

